# Generated by Django 2.2.3 on 2019-07-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='customers',
            new_name='customer',
        ),
    ]
