# Generated by Django 2.2.3 on 2019-08-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_auto_20190812_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
