# Generated by Django 2.2.3 on 2019-07-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_auto_20190718_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
    ]
