# Generated by Django 3.0.5 on 2020-05-27 21:50

from django.db import migrations, models


def remove_spaces_from_company_name(apps, schema_editor):
    Company = apps.get_model('scheduling', 'Company')
    db_alias = schema_editor.connection.alias
    companies = list(Company.objects.using(db_alias).filter(name__contains=' '))
    for company in companies:
        company.name = company.name.replace(' ', '-')
        company.save()


class Migration(migrations.Migration):
    dependencies = [
        ('scheduling', '0003_service_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RunPython(remove_spaces_from_company_name)
    ]
