# Generated by Django 2.2.3 on 2019-07-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_auto_20190718_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='start',
        ),
    ]
