# Generated by Django 2.2.3 on 2019-07-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_auto_20190720_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='instagram',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
