# Generated by Django 2.2.3 on 2019-09-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customer_notes',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
