# Generated by Django 2.2.3 on 2019-09-05 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_appointment_customer_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start',
        ),
        migrations.CreateModel(
            name='BaseAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='baseappointment_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduling.BaseAppointment'),
            preserve_default=False,
        ),
    ]
