# Generated by Django 2.2.3 on 2019-09-05 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_auto_20190905_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseappointment',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 5, 22, 59, 24, 985987)),
            preserve_default=False,
        ),
    ]
