# Generated by Django 3.0.7 on 2020-06-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_auto_20200619_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
