# Generated by Django 3.0.7 on 2020-06-23 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_auto_20200620_1607'),
    ]

    operations = [
        migrations.RunSQL('delete from scheduling_appointment where customer_id is null'),

        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_received', to='scheduling.Person'),
        ),
    ]
