# Generated by Django 2.2.3 on 2019-09-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_auto_20190915_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
