# Generated by Django 2.2.3 on 2019-09-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_auto_20190915_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='surname',
            new_name='last_name',
        ),
    ]
