# Generated by Django 2.2.3 on 2019-09-15 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_auto_20190915_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduling.Person')),
            ],
            bases=('scheduling.person',),
        ),
        migrations.AlterField(
            model_name='Appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Customer'),
        ),
    ]
