# Generated by Django 3.0.7 on 2020-08-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0021_auto_20200727_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='customer_notes',
        ),
        migrations.AddField(
            model_name='appointment',
            name='lock_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='request',
            name='customer_notes',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
