# Generated by Django 3.0.7 on 2020-08-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0031_auto_20200824_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='stripe_payment_intent_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
