# Generated by Django 3.0.7 on 2020-08-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0033_auto_20200826_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='stripe_id',
            new_name='_stripe_customer_id',
        ),
    ]
