# Generated by Django 3.0.7 on 2020-09-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0035_auto_20200828_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='name',
        ),
    ]
