# Generated by Django 3.0.7 on 2020-09-14 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0036_remove_shift_name'),
    ]

    operations = [
        migrations.RunSQL('''update scheduling_schedule
                              set mon_id = null
                              , tue_id = null
                              , wed_id = null
                              , thu_id = null
                              , fri_id = null
                              , sat_id = null
                              , sun_id = null;'''),
        migrations.RunSQL('delete from scheduling_timeframe;'),
        migrations.RunSQL('delete from scheduling_shift;'),
    ]
