# Generated by Django 3.0.7 on 2020-11-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0038_auto_20200914_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'permissions': [('overlap_appointment', 'Can overlap appointment')]},
        ),
    ]
