# Generated by Django 3.0.7 on 2020-12-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0039_auto_20201122_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
