# Generated by Django 3.0.7 on 2021-01-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0043_auto_20201228_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
