# Generated by Django 3.0.7 on 2021-01-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0046_auto_20210128_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(null=True, to='scheduling.Service'),
        ),
    ]
