# Generated by Django 3.0.14 on 2021-06-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0049_customer_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='warning',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
