# Generated by Django 3.0.14 on 2021-05-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_paymentintent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='amount_received',
            field=models.IntegerField(default=0),
        ),
    ]
