# Generated by Django 3.0.7 on 2020-09-01 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0035_auto_20200828_1413'),
        ('core', '0004_groupprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_link', to='scheduling.Employee'),
        ),
    ]
