# Generated by Django 3.0.7 on 2020-12-02 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0040_auto_20201202_1645'),
        ('core', '0005_user_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_link', to='scheduling.Employee'),
        ),
    ]
