# Generated by Django 3.0.7 on 2021-01-04 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0045_auto_20210103_2109'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConnectedAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=255, null=True, unique=True)),
                ('details_submitted', models.BooleanField(default=False)),
                ('charges_enabled', models.BooleanField(default=False)),
                ('payouts_enabled', models.BooleanField(default=False)),
                ('default_currency', models.CharField(max_length=20, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Company')),
            ],
        ),
    ]
