# Generated by Django 2.2.3 on 2020-03-04 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduling.Person')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Company')),
            ],
            bases=('scheduling.person',),
        ),
    ]
