# Generated by Django 3.0.5 on 2020-06-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_auto_20200605_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
