# Generated by Django 3.0.5 on 2020-06-06 16:53

from django.db import migrations, models
import django.db.models.deletion


def add_owner_to_appointments(apps, schema_editor):
    Appointment = apps.get_model('scheduling', 'Appointment')
    db_alias = schema_editor.connection.alias
    appointments = list(Appointment.objects.using(db_alias).all())
    for appointment in appointments:
        appointment.owner_id = appointment.employee.owner_id
        appointment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_appointment_internal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.Company'),
        ),

        migrations.RunPython(add_owner_to_appointments),

        migrations.AlterField(
            model_name='appointment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Company'),
        ),
    ]



