# Generated by Django 3.0.7 on 2020-06-23 20:28

from django.db import migrations, models
import django.db.models.deletion
import scheduling.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_auto_20200623_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scheduling.Company')),
                ('pre_book_warn', models.CharField(default='', max_length=255)),
                ('post_book_message', models.CharField(default='', max_length=255)),
                ('post_book_email_message', models.CharField(default='', max_length=255)),
                ('appointment_reminder_message', models.CharField(default='', max_length=255)),
                ('appointment_accepted_message', models.CharField(default='', max_length=255)),
                ('appointment_rejected_message', models.CharField(default='', max_length=255)),
            ],
            bases=(scheduling.models.CleanSaveMixin, models.Model),
        ),
    ]
