# Generated by Django 3.0.7 on 2020-06-26 20:58
from django.db import migrations, models
import django.db.models.deletion
import scheduling.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_service_is_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('employees', models.ManyToManyField(to='scheduling.Employee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Company')),
            ],
            bases=(scheduling.models.CleanSaveMixin, models.Model),
        ),
    ]
