# Generated by Django 3.0.7 on 2020-06-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_schedulingpanel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingpanel',
            name='employees',
            field=models.ManyToManyField(null=True, to='scheduling.Employee'),
        ),
    ]
