# Generated by Django 3.0.7 on 2020-07-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0017_auto_20200701_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='post_book_email_message',
            field=models.CharField(default='', max_length=2550),
        ),
    ]
