# Generated by Django 3.0.7 on 2020-08-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0025_historicalappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
