# Generated by Django 3.0.7 on 2020-08-17 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0026_request__status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='scheduled_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 13, 30, 20, 620637)),
            preserve_default=False,
        ),
    ]
