# Generated by Django 3.0.7 on 2020-08-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0028_auto_20200820_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='appointment_accepted_message',
            field=models.CharField(default='', max_length=2550),
        ),
        migrations.AlterField(
            model_name='config',
            name='appointment_rejected_message',
            field=models.CharField(default='', max_length=2550),
        ),
        migrations.AlterField(
            model_name='config',
            name='appointment_reminder_message',
            field=models.CharField(default='', max_length=2550),
        ),
        migrations.AlterField(
            model_name='config',
            name='post_book_message',
            field=models.CharField(default='', max_length=2550),
        ),
        migrations.AlterField(
            model_name='config',
            name='pre_book_warn',
            field=models.CharField(default='', max_length=2550),
        ),
    ]
