# Generated by Django 3.0.7 on 2020-08-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0029_auto_20200822_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
