# Generated by Django 3.0.7 on 2020-08-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0030_company_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
