# Generated by Django 3.0.7 on 2020-08-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0032_request_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='stripe_payment_intent_id',
            new_name='_stripe_payment_intent_id',
        ),
        migrations.AddField(
            model_name='request',
            name='_stripe_is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='_stripe_total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
