# Generated by Django 3.0.7 on 2020-09-14 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0037_a'),
    ]

    operations = [
        migrations.RunSQL('delete from scheduling_shift;'),
        migrations.RemoveField(
            model_name='shift',
            name='owner',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fri', to='scheduling.Shift', unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='mon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mon', to='scheduling.Shift', unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sat', to='scheduling.Shift', unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sun', to='scheduling.Shift', unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thu', to='scheduling.Shift', unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tue', to='scheduling.Shift', unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wed', to='scheduling.Shift', unique=True),
        ),
    ]
