# Generated by Django 3.0.7 on 2020-09-14 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0037_auto_20200914_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='fri',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fri', to='scheduling.Shift'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='mon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mon', to='scheduling.Shift'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sat', to='scheduling.Shift'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sun',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sun', to='scheduling.Shift'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thu', to='scheduling.Shift'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tue', to='scheduling.Shift'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wed', to='scheduling.Shift'),
        ),
    ]
