# Generated by Django 3.0.7 on 2020-12-28 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('scheduling', '0042_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='service_received', to='scheduling.Person'),
        ),

        # Fix self appointments to have customer id set to null
        migrations.RunSQL('''
                            UPDATE scheduling_appointment
                            SET customer_id = NULL
                            WHERE customer_id IN (select person_ptr_id from scheduling_employee);
                            '''),

        # Remove appointments created by users
        migrations.RunSQL('''
                            DELETE
                            FROM scheduling_appointment
                            WHERE customer_id NOT IN (select person_ptr_id from scheduling_customer)
                              and customer_id NOT IN (select person_ptr_id from scheduling_employee)
                              and service_id is not null;
                            '''),

        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='service_received', to='scheduling.Customer'),
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='scheduling.Customer'),
        ),
    ]
