# Generated by Django 3.0.7 on 2021-01-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0045_auto_20210103_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
