# Generated by Django 3.0.7 on 2021-01-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0047_auto_20210128_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='_stripe_is_paid',
        ),
        migrations.RemoveField(
            model_name='request',
            name='_stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='_stripe_total_paid',
        ),
    ]
