# Generated by Django 3.0.7 on 2020-12-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201202_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='person',
        ),
    ]
